routes/web.php
<?php
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


        Route::group(['prefix' => 'admin'], function () {
            Voyager::routes();
        });
      /**
         * Pages route 
         */

    // about routes...
    Route::get('/about', 'PagesController@getAbout'); 
    
    // communautes routes..
    Route::get('/communautes', 'PagesController@getCommunautes'); 

    //  contact routes..
    Route::get('/contact', 'PagesController@getContact'); 
    
    //  categories routes..
    Route::get('/news', 'PagesController@getnews'); 
    Route::get('/science', 'PagesController@getscience'); 
    Route::get('/high-tech', 'PagesController@gethightech'); 
    Route::get('/politique', 'PagesController@getpolitique'); 
    Route::get('/search', 'PagesController@getSearch'); 



    /**
    * session routes
    */
    Auth::routes();

    // Route::get('/dashboard', 'PagesController@getDashboard',['middleware' => 'auth', function()
    // {
    //     //
    //     Route::get('/dashboard', 'PagesController@getDashboard'); 

    // }]);
    // Home routes...
    Route::get('/home', 'PagesController@getHome')->name('home'); 
    Route::get('/', 'PagesController@getHome')->name('home'); 
    // dashboard
    Route::get('/dashboard', 'PagesController@getDashboard')->name('dashboard'); 
    // list member dashboard
    Route::get('/dashboard/member', 'PagesController@getDashboardmembres')->name('dashboard.member'); 
    // post dashboard routes...
    Route::get('/dashboard/posts', 'PagesController@getDashboardpost')->name('dashboard.posts'); 
    Route::get('/dashboard/posts/create', 'PostsController@create')->name('dashboard.posts.create'); 
    
    // account dashboard routes..
    Route::resource('dashboard/account','UserController');
    Route::get('dashboard/account/edit/','UserController@edit');
    // post routes...
    Route::resource('post','PostsController');

    // post slug routes
    Route::get('/poste/{slug}-{id}/', 'PostsController@show');
    // Route::resource('poste','PostsController');

Route::group(['middleware' => ['web']], function (){
    
  

        // Route::group(array('before' => 'auth'), function()
    // {
        // post routes...
        // Route::resource('profile','UserController');
        // Route::get('profile/edit','UserController@edit');
        // post routes...
        // Route::resource('post','PostsController');
        // Route::get('/post/{$id}/edit','PostsController@edit');
    // });
});

resources/views/pages/about.blade.php
@extends('layouts.app')
@section('title')
    abouts 
@endsection
@section('script')
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

@endsection
@section('content')
<img src="./storage/images/February2018/0ir4sRVUAJe7qnoSB0yJ.png">

    <h1>About</h1>
@endsection

resources/views/pages/communautes.blade.php
@extends('layouts.app')
@section('title')
    communautes
@endsection
@section('script')
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    @section('content')
                        <div class="col-sm-12">
                        @if(count($users) > 0)

                            
                            <table class="table table-hover dataTable no-footer">
                                    <thead>
                                      <tr>
                                        <th>id</th>
                                        <th>nom</th>
                                        <th>Email</th>
                                        <th>Avatar</th>
                                        <th>inscrit depuis</th>

                                      </tr>
                                    </thead>
                                    @foreach ($users as $user)
                                    <tbody>
                                      <tr>
                                        <td>{!!$user->id!!}</td>
                                        @if($user->role_id == '1')
                                        <td style="color:red">{!!$user->name!!}</td>
                                        @elseif($user->role_id == '2')
                                        <td style="color:blue">{!!$user->name!!}</td>
                                        @endif
                                        <td>{!!$user->email!!}</td>
                                        <td> <img class="profile-img" src="./storage/{!!$user->avatar!!}"> </td>
                                        <td>{!!$user->created_at!!}</td>
                                      </tr>      
                                    </tbody>
                                    @endforeach
                                  </table>
                            
                            
                        
                            @endif
                            </div>
                        @endsection
                    
                    {{--  @section('sidebar')
                        @parent
                        <p>this is appended to the sidebar</p>
                    @endsection  --}}
                    

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/pages/contact.blade.php
@extends('layouts.app')
@section('title')
    contact 
@endsection
@section('script')
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

@endsection
@section('content')
<div class="container">
    <h1>Contact</h1>
    {!! Form::open(['url' => 'contact/submit']) !!}
    <div class="form-group">
            {{Form::label('name', 'Name')}}
           <br>
            {{Form::text('name', '', ['class' =>'form-control','placeholder'=>'enter name'])}}
        </div>   
    <div class="form-group">
        {{Form::label('Email', 'E-Mail Address')}}
       <br>
        {{Form::text('mail', '', ['class' =>'form-control','placeholder'=>'enter E-Mail Address'])}}
    </div>
    <div class="form-group">
        {{Form::label('Message', 'Message')}}
       <br>
        {{Form::textarea('message', '', ['class' =>'form-control','placeholder'=>'enter Message'])}}
    </div>      
    <div class="form-group">
            {{Form::submit('Submit', ['class' =>'btn btn-primary'])}}
    </div>  
    {!! Form::close() !!}
</div>


@endsection

resources/views/pages/dashboard.blade.php
@extends('layouts.app')
@if (Auth::user())
@section('title')
    dashboard 
@endsection
@section('script')
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
@endsection
@section('content')
            <div class="col-md-12">

                <div class="col-md-4">
                    <ul>
                        <li class="title-menu">MENU</li>
                        <li id="dashboard" class="active"><i class="fas fa-tachometer-alt fa-lg"></i><a href="{{ route('dashboard') }}">Tableau de bord</a></li>
                        <li id="membres"><i class="fas fa-users fa-lg"></i><a href="{{ route('dashboard.member') }}"> Member</a></li>
                        <li id="publications"><i class="far fa-newspaper fa-lg"></i><a href="{{ route('dashboard.posts') }}"> Actualités</a></li>
                    </ul>
                    <ul>
                        <li class="title-menu">FONCTIONNALITÉS</li>
                        {{-- <li id="ajoutMembre"><i class="fa fa-plus-circle fa-lg"></i> Ajouter un membre</li> --}}
                        <li id="ajoutArticle" ><i class="fa fa-plus-circle fa-lg"></i><a href="{{ route('dashboard.posts.create') }}"> Ajouter une actualité </a></li>
                    </ul>
                    <ul>
                        <li class="title-menu">RÉGLAGES</li>
                        <li id="compte"><i class="fa fa-cog fa-lg"></i><a href="{{ route('account.index') }}"> Mon compte</a></li>
                        <li id="index"><i class="fa fa-power-off fa-lg"></i><a href="{{ route('logout') }}"  onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();"> Déconnexion</a></li>
                    </ul>
                </div>
                {{--  <a class="nav-link btn btn-success btn-add-new" href="post/create"><i class="voyager-plus"></i>Add New</a>  --}}
                <div class="col-md-8">
                    <div class="col-md-6">
                        <div class="panel widget center bgimage" style="height: 200px;
                        margin-bottom:0;overflow:hidden;background-image:url('http://127.0.0.1:8000/vendor/tcg/voyager/assets/images/widget-backgrounds/02.jpg');">
                            <div class="dimmer"></div>
                            <div class="panel-content">
                                <i class="voyager-news"></i><h4>{{ $posts_count }} Posts</h4>
                                <p>la base de donnée indique que il y a {{ $posts_count }} Posts au total. <br> Click sur button pour afficher tout les posts.</p>
                                <a href="{{ route('dashboard.posts') }}" class="btn btn-primary">View my posts</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="panel widget center bgimage" style="height: 200px;margin-bottom:0;overflow:hidden;background-image:url('http://127.0.0.1:8000/vendor/tcg/voyager/assets/images/widget-backgrounds/02.jpg');">
                            <div class="dimmer"></div>
                            <div class="panel-content">
                                <i class="voyager-news"></i><h4>{{ $users_count }} users</h4>
                                <p>Il  y a actuellement {{ $users_count }} users sur la database. <br> Click sur button pour afficher les utilisateur.</p>
                                <a href="{{ route('dashboard.member') }}" class="btn btn-primary">View all users</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-8 col-md-offset-2">
                        <div class="panel widget center bgimage" style="height: 200px;margin-bottom:0;overflow:hidden;background-image:url('http://127.0.0.1:8000/vendor/tcg/voyager/assets/images/widget-backgrounds/02.jpg');">
                            <div class="dimmer"></div>
                            <div class="panel-content">
                                <i class="voyager-news"></i><h4>{{ $category_count }} category</h4>
                                <p>Le site contient au total {{ $category_count }} category.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
                        
@endsection
@else
        <script>window.location.href = "/login";</script>   
@endif

resources/views/pages/high-tech.blade.php
@extends('layouts.app')
@section('title')
    News 
@endsection
@section('content')
    <div class="container-fluid">        
        <div class="row">
            <div class="col-md-12">
                {!! Form::open(['method'=>'GET','url'=>'high-tech','class'=>'navbar-form navbar-left','role'=>'search'])  !!}                       
                    <div class="input-group custom-search-form">
                        	<input  type="search" name="search" placeholder="Search">

                        <span class="input-group-btn">
                        </span>
                    </div>        
                {!! Form::close() !!}
            </div>
        

        </div>
        <section id="news" style="background: rgb(193, 193, 193);">
                    <div class="bord_rubrique">
                        <h1 class="entete_deroule tt5">News high-tech</h1>
                    </div>
                    <div class="container">
                            <div class="d-flex">
                      
                              @if(count($posts) > 1)
                                      
                                  @foreach ($posts as $post)
                                        <div class="tflex-content">
                                          <div class="div-article-home">
                                              <div class="post-image" style="background:url('@if( !filter_var($post->image, FILTER_VALIDATE_URL)){{ Voyager::image( $post->image ) }}@else{{ $post->image }}@endif')">
                                                  <div class="post-author">{{ $post->category->name}}</div>
                                              </div>
                                              <div class="post-card">
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-title">{!!$post->title!!}</a>
                                                  <div class="post-date">{{ $post->created_at}}</div>
                                                  <div class="post-content"style="">
                                                      <p>{!! $post->excerpt !!} </p>
                                                  </div>
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-read">Read More</a>
                                              </div> 
                                          </div> 
                                        </div>
                                  @endforeach  
                      
                              @else
                                  <h1><strong>Aucun article n'a été publié veuiller revenir plus tard</strong></h1>
                              @endif
                      
                            </div>      
                          </div>    
            </section>
            <div class="panel-heading" style="display:flex; justify-content:center;align-items:center;">
                {{$posts->links()}}
            </div>  
        </div>
    </div>
@endsection
{{--  @auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest  --}}

resources/views/pages/jeux.blade.php
@extends('layouts.app')
@section('title')
    Games 
@endsection
@section('content')
    <div class="container-fluid">        
        <div class="row">

            
            
                <div class="col-md-12">
                    {!! Form::open(['method'=>'GET','url'=>'games','class'=>'navbar-form navbar-left','role'=>'search'])  !!}                       
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" name="search" placeholder="Search...">
                            <span class="input-group-btn">
                            <button class="btn btn-default-sm" type="submit">recherche</button>
                            </span>
                        </div>        
                    {!! Form::close() !!}
                </div>
            </div>
                <div class="row">    
                    <div id="jeux">
                        <h1>Science/High-Tech</h1>
                        @if(count($posts) > 0)
                            @foreach ($posts as $post)
                            {{-- condition pour afficher la categorie  --}}
                                @if ($post->category_id = str_replace('2', 'Jeux', $post->category_id)) 
                                
                                {{--  {{ $post->category_id = str_replace('1', ' actualite', $post->category_id) }}  --}}
                                   
                                    {{-- condition pour afficher un article publier  --}}
                                
                                    @if ($post->status == 'PUBLISHED')
                                    
                                        <div class="col-md-3 col-lg-3">
                                            <ul class="col" data-id="{{$post->id}}">                        
                                                            {{--  choix 1  --}}
                                                    <li class="bcolor">
                                                        <a href="post/{{ $post->id }}/">
                                                            <img src="@if( !filter_var($post->image, FILTER_VALIDATE_URL)){{ Voyager::image( $post->image ) }}@else{{ $post->image }}@endif"
                                                                    class="img-responsive img-height"
                                                                    alt="{{ $post->title }} avatar">
                                                                <h3>{!!$post->title!!}</h3>
                                                                <p class="">{!!$post->excerpt!!}</p>
                                                            </a>
                                                            {{--  <span class="label">{!!$post->body!!}</span>  --}}
                                                            <a href="#jeux" class="tag">{{ $post->category_id}} </a>
                                                    </li>
                                            </ul>
                                        </div>
                        
                                    @endif        
                                @else
                                @endif
                            @endforeach      
                        @else
                        <h1><strong>Aucun article n'a été publié veuiller revenir plus tard</strong></h1>
                        @endif
                    </div>
                </div>
                    <div class="panel-heading" style="display:flex; justify-content:center;align-items:center;">
                        {{$posts->links()}}
                    </div>  
                </div>
            
        </div>
    </div>
@endsection
{{--  @auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest  --}}

resources/views/pages/news.blade.php
@extends('layouts.app')
@section('title')
    News 
@endsection
@section('content')
    <div class="container-fluid">        
        <div class="row">
            <div class="col-md-12">
                {!! Form::open(['method'=>'GET','url'=>'news','class'=>'navbar-form navbar-left','role'=>'search'])  !!}                       
                <div class="input-group custom-search-form">
                        <input  type="search" name="search" placeholder="Search">
                        <span class="input-group-btn">
                        </span>
                    </div>  
                {!! Form::close() !!}
            </div>
        

        </div>
        <section id="news" style="background: rgb(193, 193, 193);">
                    <div class="bord_rubrique">
                        <h1 class="entete_deroule tt5">News World</h1>
                    </div>
                    <div class="container">
                            <div class="d-flex">
                      
                              @if(count($posts) > 1)
                                      
                                  @foreach ($posts as $post)
                                        <div class="tflex-content">
                                          <div class="div-article-home">
                                              <div class="post-image" style="background:url('@if( !filter_var($post->image, FILTER_VALIDATE_URL)){{ Voyager::image( $post->image ) }}@else{{ $post->image }}@endif')">
                                                  <div class="post-author">{{ $post->category->name}}</div>
                                              </div>
                                              <div class="post-card">
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-title">{!!$post->title!!}</a>
                                                  <div class="post-date">{{ $post->created_at}}</div>
                                                  <div class="post-content"style="">
                                                      <p>{!! $post->excerpt !!} </p>
                                                  </div>
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-read">Read More</a>
                                              </div> 
                                          </div> 
                                        </div>
                                  @endforeach  
                      
                              @else
                                  <h1><strong>Aucun article n'a été publié veuiller revenir plus tard</strong></h1>
                              @endif
                      
                            </div>      
                          </div>    
            </section>
            <div class="panel-heading" style="display:flex; justify-content:center;align-items:center;">
                {{$posts->links()}}
            </div>  
        </div>
    </div>
@endsection
{{--  @auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest  --}}

resources/views/pages/politique.blade.php
@extends('layouts.app')
@section('title')
    News 
@endsection
@section('content')
    <div class="container-fluid">        
        <div class="row">
            <div class="col-md-12">
                {!! Form::open(['method'=>'GET','url'=>'politique','class'=>'navbar-form navbar-left','role'=>'search'])  !!}                       
                    <div class="input-group custom-search-form">
                            <input  type="search" name="search" placeholder="Search">
                            <span class="input-group-btn">
                            </span>
                    </div>        
                {!! Form::close() !!}
            </div>
        

        </div>
        <section id="news" style="background: rgb(193, 193, 193);">
                    <div class="bord_rubrique">
                        <h1 class="entete_deroule tt5">News politique</h1>
                    </div>
                    <div class="container">
                            <div class="d-flex">
                      
                              @if(count($posts) > 0)
                                      
                                  @foreach ($posts as $post)
                                        <div class="tflex-content">
                                          <div class="div-article-home">
                                              <div class="post-image" style="background:url('@if( !filter_var($post->image, FILTER_VALIDATE_URL)){{ Voyager::image( $post->image ) }}@else{{ $post->image }}@endif')">
                                                  <div class="post-author">{{ $post->category->name}}</div>
                                              </div>
                                              <div class="post-card">
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-title">{!!$post->title!!}</a>
                                                  <div class="post-date">{{ $post->created_at}}</div>
                                                  <div class="post-content"style="">
                                                      <p>{!! $post->excerpt !!} </p>
                                                  </div>
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-read">Read More</a>
                                              </div> 
                                          </div> 
                                        </div>
                                  @endforeach  
                      
                              @else
                                  <h1><strong>Aucun article n'a été publié veuiller revenir plus tard</strong></h1>
                              @endif
                      
                            </div>      
                          </div>    
            </section>
            <div class="panel-heading" style="display:flex; justify-content:center;align-items:center;">
                {{$posts->links()}}
            </div>  
        </div>
    </div>
@endsection
{{--  @auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest  --}}

resources/views/pages/science.blade.php
@extends('layouts.app')
@section('title')
    News 
@endsection
@section('content')
    <div class="container-fluid">        
        <div class="row">
            <div class="col-md-12">
                {!! Form::open(['method'=>'GET','url'=>'science','class'=>'navbar-form navbar-left','role'=>'search'])  !!}                       
                    <div class="input-group custom-search-form">
                            <input  type="search" name="search" placeholder="Search">
                            <span class="input-group-btn">
                            </span>
                    </div>        
                {!! Form::close() !!}
            </div>
        

        </div>
        <section id="news" style="background: rgb(193, 193, 193);">
                    <div class="bord_rubrique">
                        <h1 class="entete_deroule tt5">News science</h1>
                    </div>
                    <div class="container">
                            <div class="d-flex">
                      
                              @if(count($posts) > 0)
                                      
                                  @foreach ($posts as $post)
                                        <div class="tflex-content">
                                          <div class="div-article-home">
                                              <div class="post-image" style="background:url('@if( !filter_var($post->image, FILTER_VALIDATE_URL)){{ Voyager::image( $post->image ) }}@else{{ $post->image }}@endif')">
                                                  <div class="post-author">{{ $post->category->name}}</div>
                                              </div>
                                              <div class="post-card">
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-title">{!!$post->title!!}</a>
                                                  <div class="post-date">{{ $post->created_at}}</div>
                                                  <div class="post-content"style="">
                                                      <p>{!! $post->excerpt !!} </p>
                                                  </div>
                                                  <a href="post/{{ $post->id }}-{{ $post->slug }}/" class="post-read">Read More</a>
                                              </div> 
                                          </div> 
                                        </div>
                                  @endforeach  
                      
                              @else
                                  <h1><strong>Aucun article n'a été publié veuiller revenir plus tard</strong></h1>
                              @endif
                      
                            </div>      
                          </div>    
            </section>
            <div class="panel-heading" style="display:flex; justify-content:center;align-items:center;">
                {{$posts->links()}}
            </div>  
        </div>
    </div>
@endsection
{{--  @auth
    // The user is authenticated...
@endauth

@guest
    // The user is not authenticated...
@endguest  --}}